import Head from 'next/head';
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
import Link from 'next/link';
import NavBar from '../components/NavBar';
import CourseList from '@/components/CourseList';
import Testimonials from '@/components/Testimonials';

export default function Home() {
  return (
    <>
      <Head>
        <title>NCT- The Course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar />
      <h1>Introducing NCT the Course</h1>
      <p> Your one stop shop for learning everything about the K-pop supergroup NCT.</p>
      <div>
        <CourseList />
      </div>
      <Testimonials />
    </>
  )
}
